# HalluLens-Style 4-Category Taxonomy
CLAUSE_TO_TYPE = {
    'Agreement Date': 'temporal',
    'Effective Date': 'temporal',
    'Expiration Date': 'temporal',
    'Renewal Term': 'temporal',
    'Notice Period To Terminate Renewal': 'temporal',
    'Warranty Duration': 'temporal',
    
    'Cap On Liability': 'numeric',
    'Liquidated Damages': 'numeric',
    'Price Restrictions': 'numeric',
    'Volume Restriction': 'numeric',
    'Minimum Commitment': 'numeric',
    
    'Non-Compete': 'obligation_entitlement',
    'Exclusivity': 'obligation_entitlement',
    'No-Solicit Of Customers': 'obligation_entitlement',
    'No-Solicit Of Employees': 'obligation_entitlement',
    'License Grant': 'obligation_entitlement',
    'Ip Ownership Assignment': 'obligation_entitlement',
    'Joint Ip Ownership': 'obligation_entitlement',
    'Non-Transferable License': 'obligation_entitlement',
    'Audit Rights': 'obligation_entitlement',
    'Insurance': 'obligation_entitlement',
    'Termination For Convenience': 'obligation_entitlement',
    'Post-Termination Services': 'obligation_entitlement',
    'Most Favored Nation': 'obligation_entitlement',
    'Competitive Restriction Exception': 'obligation_entitlement',
    'Non-Disparagement': 'obligation_entitlement',
    'Rofr/Rofo/Rofn': 'obligation_entitlement',
    'Change Of Control': 'obligation_entitlement',
    'Anti-Assignment': 'obligation_entitlement',
    'Revenue/Profit Sharing': 'obligation_entitlement',
    'Affiliate License-Licensor': 'obligation_entitlement',
    'Affiliate License-Licensee': 'obligation_entitlement',
    'Unlimited/All-You-Can-Eat-License': 'obligation_entitlement',
    'Irrevocable Or Perpetual License': 'obligation_entitlement',
    'Source Code Escrow': 'obligation_entitlement',
    'Uncapped Liability': 'obligation_entitlement',
    'Covenant Not To Sue': 'obligation_entitlement',
    'Third Party Beneficiary': 'obligation_entitlement',
    
    'Document Name': 'factual',
    'Parties': 'factual',
    'Governing Law': 'factual'
}

# Define All 41 CUAD Clause Definitions (from official dataset)
CLAUSE_DEFINITIONS =  ['"Document Name" : The name of the contract',
 '"Parties" : The two or more parties who signed the contract',
 '"Agreement Date" : The date of the contract',
 '"Effective Date" : The date when the contract is effective. NOTE: This requires a clause or statement that establishes WHEN the agreement takes effect (e.g. \"effective as of [date]\", \"shall be effective immediately\", \"Effective Date means...\"). A mere \"Dated:\" line in the signature block or document heading, WITHOUT any accompanying language about when the agreement becomes effective, is NOT sufficient on its own.',
 '"Expiration Date" : On what date will the contract\'s initial term expire?',
 '"Renewal Term" : What is the renewal term after the initial term expires? This includes automatic extensions and unilateral extensions with prior notice.',
 '"Notice Period To Terminate Renewal" : What is the notice period required to terminate renewal?',
 '"Governing Law" : Which state/country\'s law governs the interpretation of the contract?',
 '"Most Favored Nation" : Is there a clause that if a third party gets better terms on the licensing or sale of technology/goods/services described in the contract, the buyer of such technology/goods/services under the contract shall be entitled to those better terms?',
 '"Non-Compete" : Is there a restriction on the ability of a party to compete with the counterparty or operate in a certain geography or business or technology sector? NOTE: This restricts market competition. An exclusive purchase obligation (a party must buy ONLY from this supplier) is NOT a Non-Compete — that is an exclusivity/supply restriction, not a market competition restriction.',
 '"Exclusivity" : Is there an exclusive dealing commitment with the counterparty? This includes a commitment to procure all "requirements" from one party of certain technology, goods, or services or a prohibition on licensing or selling technology, goods or services to third parties, or a prohibition on collaborating or working with other parties, whether during the contract or after the contract ends (or both). NOTE: The visible contract text must CONFIRM the exclusive obligation. A section heading or label (e.g. "Exclusivity") with all content redacted ([ * ] or similar) is NOT confirmed evidence — the visible text must affirmatively state the exclusive commitment.',
 '"No-Solicit Of Customers" : Is a party restricted from contracting or soliciting customers or partners of the counterparty, whether during the contract or after the contract ends (or both)? NOTE: This restricts soliciting the counterparty\'s CUSTOMERS or PARTNERS specifically. A restriction on distributing or selling PRODUCTS to third parties is a product distribution restriction, NOT a No-Solicit Of Customers clause. The clause must target the solicitation of specific customer/partner RELATIONSHIPS.',
 '"Competitive Restriction Exception" : This category includes the exceptions or carveouts to Non-Compete, Exclusivity and No-Solicit of Customers above.',
 '"No-Solicit Of Employees" : Is there a restriction on a party’s soliciting or hiring employees and/or contractors from the\xa0 counterparty, whether during the contract or after the contract ends (or both)?',
 '"Non-Disparagement" : Is there a requirement on a party not to disparage the counterparty? NOTE: This requires an explicit obligation not to DISPARAGE or make NEGATIVE STATEMENTS about the counterparty. A general prohibition on posting "libelous or harmful" content on a platform is a content policy, NOT a Non-Disparagement clause — it applies to all content, not statements about the counterparty specifically.',
 '"Termination For Convenience" : Can a party terminate this\xa0 contract without cause (solely by giving a notice and allowing a waiting\xa0 period to expire)? NOTE: This requires an EXPLICIT, standalone right to terminate without cause by giving notice. A hypothetical reference to termination without cause inside another clause (e.g. a repurchase or remedy clause that says "if Company terminates without cause") does NOT establish a Termination For Convenience right — it merely describes consequences of an event. The contract must grant the RIGHT to terminate, not just mention the possibility.',
 '"Rofr/Rofo/Rofn" : Is there a clause granting one party a right of first refusal, right of first offer or right of first negotiation to purchase, license, market, or distribute equity interest, technology, assets, products or services?',
 '"Change Of Control" : Does one party have the right to terminate or is consent or notice required of the counterparty if such party undergoes a change of control, such as a merger, stock sale, transfer of all or substantially all of its assets or business, or assignment by operation of law? NOTE: This governs corporate-level ownership/control transfers (mergers, acquisitions, majority ownership changes). An anti-assignment clause (requiring consent before assigning CONTRACT RIGHTS to a third party) is NOT a Change Of Control clause.',
 '"Anti-Assignment" : Is consent or notice required of a party if the contract is assigned to a third party?',
 '"Revenue/Profit Sharing" : Is one party required to share revenue or profit with the counterparty for any technology, goods, or services? NOTE: This requires one party to receive a PERCENTAGE of the other party\'s gross revenue or profit. A flat fee, per-unit payment, or cost reimbursement is NOT Revenue/Profit Sharing.',
 '"Price Restrictions" : Is there a restriction on the\xa0 ability of a party to raise or reduce prices of technology, goods, or\xa0 services provided? NOTE: This restricts the PRICING DISCRETION of a party — their ability to SET or CHANGE prices. A payment cap or maximum payment amount (e.g. "total payments shall not exceed $X") is a PAYMENT LIMIT, not a Price Restriction. The clause must restrict the price of the goods/services themselves, not the total amount payable.',
 '"Minimum Commitment" : Is there a minimum order size or minimum amount or units per-time period that one party must buy from the counterparty under the contract? NOTE: This includes purchase minimums, order minimums, AND performance minimums (e.g. minimum number of events, activities, or services a party must perform). A recurring fixed service fee (e.g. monthly hosting fee) where no minimum quantity is specified is less likely to qualify.',
 '"Volume Restriction" : Is there a fee increase or consent requirement, etc. if one party\'s use of the product/services exceeds certain threshold? NOTE: This is an explicit MAXIMUM CAP or threshold on usage/quantity that triggers a fee or consent requirement. Minimum purchase quotas (requiring a party to buy at least X) are NOT Volume Restrictions.',
 '"Ip Ownership Assignment" : Does intellectual property created by one party become the property of the counterparty, either per the terms of the contract or upon the occurrence of certain events? NOTE: The IP must be CREATED DURING or under the contract and then assigned/transferred to the counterparty. Acknowledging pre-existing IP ownership (IP that existed before the contract) is NOT an IP Ownership Assignment.',
 '"Joint Ip Ownership" : Is there any clause providing for joint or shared ownership of intellectual property between the parties to the contract?',
 '"License Grant" : Does the contract contain a license granted by one party to its counterparty?',
 '"Non-Transferable License" : Does the contract limit the ability of a party to transfer the license being granted to a third party? NOTE: This requires an explicit prohibition on TRANSFERRING or ASSIGNING the LICENSE ITSELF to a third party. A restriction on distributing, selling, or sublicensing PRODUCTS (the output of the licensed technology) is a product distribution restriction, NOT a Non-Transferable License. General assignment clauses on the contract as a whole (not the license specifically) do NOT qualify. The restriction must target the LICENSE GRANT, not product distribution.',
 '"Affiliate License-Licensor" : Does the contract contain a license grant by affiliates of the licensor or that includes intellectual property of affiliates of the licensor?\xa0',
 '"Affiliate License-Licensee" : Does the contract contain a license grant to a licensee (incl. sublicensor) and the affiliates of such licensee/sublicensor?',
 '"Unlimited/All-You-Can-Eat-License" : Is there a clause granting one party an “enterprise,” “all you can eat” or unlimited usage license?',
 '"Irrevocable Or Perpetual License" : Does the contract contain a\xa0 license grant that is irrevocable or perpetual?',
 '"Source Code Escrow" : Is one party required to deposit its source code into escrow with a third party, which can be released to the counterparty upon the occurrence of certain events (bankruptcy,\xa0 insolvency, etc.)?',
 '"Post-Termination Services" : Is a party subject to obligations after the termination or expiration of a contract, including any post-termination transition, payment, transfer of IP, wind-down, last-buy, or similar commitments? NOTE: This requires ACTIVE DELIVERABLES or affirmative obligations owed AFTER contract expiry. Mere cessation of rights (e.g. license ends), a final payment already owed during the term, or return of materials alone are NOT Post-Termination Services.',
 '"Audit Rights" : Does a party have the right to\xa0 audit the books, records, or physical locations of the counterparty to ensure compliance with the contract?',
 '"Uncapped Liability" : Is a party’s liability uncapped upon the breach of its obligation in the contract? This also includes uncap liability for a particular type of breach such as IP infringement or breach of confidentiality obligation.',
 '"Cap On Liability" : Does the contract include a cap on liability upon the breach of a party\'s obligation? This includes time limitation for the counterparty to bring claims or maximum amount for recovery. NOTE: This requires an explicit maximum amount or formula capping liability. A clause that ONLY excludes certain types of damages (e.g. no consequential damages) without stating a maximum liability amount is typically not a Cap On Liability.',
 '"Liquidated Damages" : Does the contract contain a clause that would award either party liquidated damages for breach or a fee upon the termination of a contract (termination fee)? NOTE: The clause must AWARD or SPECIFY a liquidated damages amount. A clause EXCLUDING or DENYING liability for liquidated damages (e.g. "no liability for liquidated damages", "party shall not be liable for liquidated damages") is the OPPOSITE — it is NOT a Liquidated Damages clause. A general consequential-damages exclusion is NOT a Liquidated Damages clause.',
 '"Warranty Duration" : What is the duration of any\xa0 warranty against defects or errors in technology, products, or services\xa0 provided under the contract?',
 '"Insurance" : Is there a requirement for insurance that must be maintained by one party for the benefit of the counterparty?',
 '"Covenant Not To Sue" : Is a party restricted from contesting the validity of the counterparty’s ownership of intellectual property or otherwise bringing a claim against the counterparty for matters unrelated to the contract?',
 '"Third Party Beneficiary" : Is there a non-contracting party who is a beneficiary to some or all of the clauses in the contract and therefore can enforce its rights against a contracting party? NOTE: The contract must EXPLICITLY grant enforceable rights to a named or identifiable non-contracting party. Mere coincidental benefit to a third party does NOT qualify. A clause DENYING third-party beneficiary rights (e.g. "no third-party beneficiaries", "nothing herein creates rights for third parties") is the OPPOSITE — it is NOT a Third Party Beneficiary clause.']
